#!/bin/sh

mysql -u root -p$MYSQL_ROOT_PASSWORD << EOQ
CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE_NC;
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE_NC.* TO '$MYSQL_USER' identified by '$MYSQL_PASSWORD';
EOQ

